{% set name = "ast2json" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ast2json-{{ version }}.tar.gz
  sha256: b5cc42e97c29b77845b5d4ec32e74dcac538fb4c61a7faa570964bc96b19aeb7

build:
  entry_points:
    - ast2json = ast2json.ast2json:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - ast2json
  commands:
    - pip check
    - "echo 'print(str(1))' > test.py; ast2json < test.py"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/YoloSwagTeam/ast2json
  summary: convert a python source code into json-dumpable data (dict and lists with strings, ints, ...)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
